### ISSUE TITLE
Not compatible with Gedit "40"

### ISSUE THREAD

**Issue by webmastak** [maoschanz/gedit-plugin-open-as-root#3]
When debugging, it produces:
```
line 68 in action_cb
admin_uri = 'admin://' + doc.get_uri_for_display()`
AttributeError: 'Document' object has no attribute 'get_uri_for_display
```

**Comment by maoschanz** [comment]
could you tell me the version of Gedit you're using?

**Comment by webmastak** [comment]
Gedit 40.0

Rolled back to Gedit 3.38 everything works

**Comment by maoschanz** [comment]
i'll not upgrade to GNOME 40 until they have usable, vertical workspaces, so you can either:

- propose a patch for this plugin if you find out how to do it;
- ask Gedit devs to finally update their f-cking documentation https://developer.gnome.org/gedit/ so plugins developers could know in advance what features are deprecated (and find alternatives without having to resort to a ouija board);
- tell GNOME Shell developers to change their horrible design.

sorry but i'm a little tired of their bullshit

**Comment by webmastak** [comment]
> sorry but i'm a little tired of their bullshit

You are not the only one, many do not like how armless developers disfigure Gnome since Gnome 2

**Comment by maoschanz** [comment]
i looked into it, and even when this specific problem is fixed it doesn't work: it seems like gedit just stopped supporting the `admin://` protocol entirely for some reason

![Capture d’écran de 2022-01-03 01-47-30](https://user-images.githubusercontent.com/19996113/147893591-94049b36-65e2-4414-b9d7-ea9d0cde9345.png)

**Comment by yochananmarqos** [comment]
> it seems like gedit just stopped supporting the admin:// protocol 

I just navigated to `/boot/efi/` in nautilus which prompts for elevated privileges. I then opened `/efi/EFI/refind/refind.conf` in gedit which is opened as `admin:///boot/efi/EFI/refind/refind.conf`.

![Screenshot from 2022-01-02 18-46-01](https://user-images.githubusercontent.com/5437803/147894955-a0c63374-6f35-4cd6-b337-fc7fc8abf20a.png)

**Comment by maoschanz** [comment]
oh ok 🤔

i guess it's either because i'm using gedit 40 in gnome 3.38 instead of 40, or because i'm using a gedit 40 which doesn't work while yours is now 41

could you try to reinstall the plugin and tell me if it works please?

**Comment by yochananmarqos** [comment]
Yes, it works. :+1:
